[package]
name = "server_fn_macro_default"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "The default implementation of the server_fn macro without a context"
version = { workspace = true }
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0" }
server_fn_macro = { workspace = true }

[features]
nightly = ["server_fn_macro/nightly"]
ssr = ["server_fn_macro/ssr"]
actix = ["server_fn_macro/actix"]
axum = ["server_fn_macro/axum"]

[package.metadata.cargo-all-features]
max_combination_size = 2
skip_feature_sets = [["nightly"]]
