[package]
name = "server_fn_macro"
version = "0.6.0"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
description = "RPC for any web framework."
readme = "../README.md"

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
proc-macro2 = "1"
xxhash-rust = { version = "0.8.6", features = ["const_xxh64"] }
const_format = "0.2.30"
convert_case = "0.6.0"

[features]
nightly = []
ssr = []
actix = []
axum = []
reqwest = []
