[package]
name = "server_fn_macro"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "RPC for any web framework."
readme = "../README.md"
version = "0.8.8"
edition.workspace = true

[dependencies]
quote = { workspace = true, default-features = true }
syn = { features = [
  "full",
  "parsing",
  "extra-traits",
], workspace = true, default-features = true }
proc-macro2 = { workspace = true, default-features = true }
xxhash-rust = { features = [
  "const_xxh64",
], workspace = true, default-features = true }
const_format = { workspace = true, default-features = true }
convert_case = { workspace = true, default-features = true }


[build-dependencies]
rustc_version = { workspace = true, default-features = true }


[features]
nightly = []
ssr = []
actix = []
axum = []
generic = []
reqwest = []

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

[package.metadata.cargo-all-features]
max_combination_size = 2
skip_feature_sets = [["nightly"]]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rustc_nightly)'] }
