[package]
name = "leptos_meta"
version = "0.7.0-beta"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "Tools to set HTML metadata in the Leptos web framework."
rust-version.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true }
once_cell = "1.19"
or_poisoned = { workspace = true }
indexmap = "2.3"
send_wrapper = "0.6.0"
tracing = "0.1.40"
wasm-bindgen = "0.2.93"
futures = "0.3.30"

[dependencies.web-sys]
version = "0.3.69"
features = ["HtmlLinkElement", "HtmlMetaElement", "HtmlTitleElement"]

[features]
default = []
ssr = []

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
