[tasks.check-minimal-versions]
condition = { channels = ["nightly"] }
command = "cargo"
args = [
  "all-features",
  "minimal-versions",
  "check",
  "--ignore-private",
  "--detach-path-deps",
  "--direct",
]
install_script = '''
cargo install cargo-all-features
'''
