[package]
name = "reactive_stores"
version = "0.4.1"
authors = ["Greg Johnston"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/leptos-rs/leptos"
description = "Stores for holding deeply-nested reactive state while maintaining fine-grained reactive tracking."
rust-version.workspace = true
edition.workspace = true

[features]
default = []
serde = ["dep:serde"]
slotmap = ["dep:slotmap"]

[dependencies]
guardian = { workspace = true, default-features = true }
itertools = { workspace = true, default-features = true }
or_poisoned = { workspace = true }
paste = { workspace = true, default-features = true }
reactive_graph = { workspace = true }
rustc-hash = { workspace = true, default-features = true }
reactive_stores_macro = { workspace = true }
send_wrapper = { workspace = true, default-features = true }
serde = { workspace = true, optional = true }
slotmap = { workspace = true, optional = true }
indexmap = { workspace = true, default-features = true }

[dev-dependencies]
tokio = { features = [
	"rt-multi-thread",
	"macros",
], workspace = true, default-features = true }
tokio-test = { workspace = true, default-features = true }
any_spawner = { workspace = true, features = ["futures-executor", "tokio"] }
reactive_graph = { workspace = true, features = ["effects"] }
leptos = { path = "../leptos", features = ["csr"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(leptos_debuginfo)'] }
