[package]
name = "client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
api-boundary = "*"

leptos = { path = "../../../leptos", features = ["csr"] }
leptos_meta = { path = "../../../meta", features = ["csr"] }
leptos_router = { path = "../../../router", features = ["csr"] }

log = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"
gloo-net = "0.6"
gloo-storage = "0.3"
serde = "1.0"
thiserror = "1.0"
