[package]
name = "client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
api-boundary = { workspace = true }

leptos = { path = "../../../leptos", features = ["csr"] }
leptos_meta = { path = "../../../meta" }
leptos_router = { path = "../../../router" }

log = "0.4.22"
console_error_panic_hook = "0.1.7"
console_log = "1.0"
gloo-net = "0.6.0"
gloo-storage = "0.3.0"
serde = "1.0"
thiserror = "1.0"
