[env]
CARGO_MAKE_WASM_TEST_ARGS = "--headless --chrome"

[tasks.test-all]
dependencies = ["test", "web-test"]

[tasks.web-test]
command = "cargo"
args = ["make", "wasm-pack-test"]

[tasks.build]
command = "cargo"
args = ["+stable", "build-all-features"]
install_crate = "cargo-all-features"

[tasks.check]
command = "cargo"
args = ["+stable", "check-all-features"]
install_crate = "cargo-all-features"
