[workspace]
resolver = "2"
members = ["client", "api-boundary", "server"]

[profile.release]
codegen-units = 1
lto = true

[patch.crates-io]
leptos = { path = "../../leptos", features = ["nightly"] }
leptos_router = { path = "../../router", features = ["nightly"] }
api-boundary = { path = "api-boundary" }
